# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, help_text=b'Client contact name', max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text=b'Client email address', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text=b'Client business address'),
        ),
    ]
