# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170620_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=b'ID'),
        ),
    ]
