# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20170804_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'issued', b'Issued'), (b'paid', b'Paid')], default=b'draft', max_length=10),
        ),
    ]
