# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='links',
            field=models.ManyToManyField(related_name='_transaction_links_+', to='ledger.Transaction'),
        ),
    ]
