# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_migrate_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='linked',
        ),
    ]
